### ISSUE TITLE
Document BTCPAY_HOST="IP" and SSL 500/503

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/btcpayserver-doc#93] opened 2018-11-05 21:25 UTC
We need to document that 503 and SSL errors a bit better somewhere and explain clearly why it happens when it happens and how to fix it.

@NicolasDorier help with this is appreciated

**Comment by NicolasDorier** [comment] 2018-11-06 02:43
I myself have no idea what it is about, when does it happeN?

**Comment by bitcoinshirt** [comment] 2018-11-08 20:11
After some testing I realized that most people having 503 errors are the ones who don't have a domain name and use manual setup or the ones forgeting to point the vp via external ip. 

Closing this one.

**Comment by bitcoinshirt** [comment] 2018-11-16 11:08
It appears that this is one of the most common issues, so I really think it should be documented, re-opening this again.

**Problem :** 

During manual installation, the user puts IP address in BTCPay host.
We advice users to put a proper domain name. They can change it manually with `export BTCPAY_HOST="domainname.com"` or via Server Settings > Change domain. In some cases they get **SSL errors** afterwards and are able to access it only through HTTP in which case we need to advise them what to do next.

**Comment by NicolasDorier** [comment] 2018-11-16 13:14
Can you give me summary of the errors and the cause you documented?

I am thinking to just have proper error pages explaining the issue that NGINX will return.

**Comment by NicolasDorier** [comment] 2018-11-16 13:15
there is: error 500, 502 and 503. I can ask nginx to give a better error page if each happen.

**Comment by NicolasDorier** [comment] 2018-11-16 13:38
Ok so I am now crashing during `btcpay-setup.sh` if it is not correct: https://github.com/btcpayserver/btcpayserver-docker/commit/6ef0cf95a848d31354acc3ddace1ed0ca1334dd2

**Comment by bitcoinshirt** [comment] 2018-11-16 15:49
So I guess that closes the issue?
I mean anything you can do to improve that would be great, I'm really seeing this asked with nearly any manual installation. 
Let me know if you need something documented, but if you fix it with code, and provide clear warring, even better.

**Comment by NicolasDorier** [comment] 2018-11-17 04:01
it does not close it. We should see precisely in which case which error is sent, and then I need to show a proper explanation page for each.

**Comment by bitcoinshirt** [comment] 2018-12-26 19:34
@NicolasDorier 
Happens:
1. When the user with manual installation uses IP. (90% of cases)
2. Happens when user uses a domain but verification fails with let's encrypt (10% of cases)

**Comment by NicolasDorier** [comment] 2019-02-03 03:12
@talentpierre this error probably mean that the server you are contacting is actually not your LND server.

**Closed** 2019-02-19 13:54 UTC
Labels: enhancement

**Comment by jmaurice** [comment] 2019-07-14 05:54
Yeah, I ran into this again today. This is not only confusing but I have a proposal how to fix it. IMO there are 3 main issues:

1) Using BTCPAY_HOST=IP should be a valid option, or more accurately, having a FQDN for the btcpay instance should be optional. If the user sets an "invalid" domain name, or no hostname is set, then this should simply trigger "insecure mode" which also sets BTCPAY_PROTOCOL=http so we don't try to get an impossible-to-obtain SSL certificate from let's encrypt (why are we doing that?)

2) I assume you locked down nginx to return 500 error page when trying to access http://IP/ to prevent insecure page access, but if the above "insecure mode" is activated, then IMO nginx should serve the btcpay UI on any hostname or IP since there is no "valid" hostname to lock the site down to, if nothing more to avoid confusing the user with a bogus 500 error

3) The 500 error page should be more helpful than "500 go away" lol :)

**Comment by jmaurice** [comment] 2019-07-14 05:56
The above "insecure mode" is super useful for a home user who's just running btcpay on a Raspberry Pi and can't open ports and/or doesn't have a static ip/hostname. In this case, they will be limited to Tor connectivity only, but that's actually totally fine for some use cases. The requirement of FQDN hostname and static IP for btcpay should be made optional IMO.

**Comment by NicolasDorier** [comment] 2019-07-14 06:07
@jmaurice btcpay consider local network IPs, onion links, and domain name ending with .lan or .local as secure.

**Comment by jmaurice** [comment] 2019-07-14 07:04
AFAIK you cannot even set BTCPAY_HOST=192.168.1.5 unless you comment out some code in btcpay-setup.sh right?

**Comment by NicolasDorier** [comment] 2019-07-14 11:52
@jmaurice try this:

```
BTCPAY_HOST=localhost
REVERSEPROXY_DEFAULT_HOST=localhost
. btcpay-setup.sh -i
```

**Comment by jmaurice** [comment] 2019-07-14 12:08
```
BTCPAYGEN_REVERSEPROXY is set to nginx, so BTCPAY_HOST must be a domain name which point to this server, but the current value of BTCPAY_HOST ('localhost') is not a valid domain name.
```

**Comment by jmaurice** [comment] 2019-07-14 12:10
FYI even if I comment that error check, it just returns 503 for http://raspberrypi.local

**Comment by NicolasDorier** [comment] 2019-07-14 12:39
@jmaurice that's pain in the ass.
On my rock64, it works by using avahi. Basically, I use `btcpay.local` which is broadcasted via mdns, and use this as `BTCPAY_HOST`.

**Comment by NicolasDorier** [comment] 2019-07-14 12:40
You can take a look on `https://github.com/dgarage/BTCPayServer-Armbian/tree/btcpay/userpatches` I install avahi in `customize-image.sh`

**Comment by jmaurice** [comment] 2019-07-15 17:42
Yes I've been using `BTCPAY_HOST=raspberrypi.local` just fine, I'm just putting in my 2 cents that this issue could be resolved by making the FQDN requirement optional since not everyone will expose their btcpay instance to the Internet. If you don't want to modify it then maybe we can just improve documentation or clarify that *.local domains are the best way to go for now. Thanks

**Comment by NicolasDorier** [comment] 2019-07-16 06:48
@jmaurice if I could I would, but this is not easy.

**Comment by pavlenex** [comment] 2019-07-16 07:36
Good idea about improving documentation for that one.

**Comment by jmaurice** [comment] 2019-07-16 17:08
Is http://raspberrypi.local/rtl supposed to work with this configuration? I get SSO error, I'm guessing it's requiring https:// login and may not have the *.local hostname exempted

**Comment by NicolasDorier** [comment] 2019-07-17 09:22
@jmaurice supposed to work if you go there by `Server Settings/ RTL`. There is cache issues sometimes which give problems, try incognito mode.
