### ISSUE TITLE
Improve Greenfield API example with Node.js (JavaScript)

### ISSUE THREAD

**Issue by spacekestrel** [btcpayserver/btcpayserver-doc#1406] opened 2024-05-23 11:18 UTC
I could not find the information I was looking for on the "Greenfield API example with Node.js (JavaScript)" page (`/Development/GreenFieldExample-NodeJS/`).
Couldn't find info on how to aquire transaction fee in pull payments.

**Comment by ndeet** [comment] 2024-06-27 08:41
this is a duplicate of https://github.com/btcpayserver/btcpayserver-doc/issues/1404

the examples show some common use cases and not the whole possibilities of the whole API, from the examples it should be trivial to browse the [API reference]([url](https://docs.btcpayserver.org/API/Greenfield/v1/)) and adjust the examples accordingly

**Closed** 2024-06-28 22:28 UTC
