### ISSUE TITLE
Please add comments in documentations - this will reduce many thousends hours of searching

### ISSUE THREAD

**Issue by didiandalucia** [btcpayserver/btcpayserver-doc#361] opened 2019-11-06 13:42 UTC
When you import an zpub key, you will see later an xpub key! No worry, this is absolute normal!

When you use electrum with btcpay, then you must understand, that not every of your client can pay why they get when they scan the btcpaying barcode the information "btcaddress is wrong". Please understand, thats this is not the problem of btcpay-server but about a problem with the electrum wallet why they generate Bech32 and many other wallets not support Bech32. The best will been, you use P2SH but about an other problem of Electrum Wallet is, that they cant generate P2SH! 

So a workarround is: Create with an other wallet an P2SH seed. You must not transfer with the other wallet money. Then you export in the other wallet the P2SH generated seed and you import this with electrum! Then you copy as written here the zpub-key with [p2sh] and then you can been happy! Please secure your seed (the 10 words) on a very good secured place, otherwise you can lost all your money on the wallet!

**Comment by pavlenex** [comment] 2019-11-15 17:13
Closing as a duplicate of #368 and will be addressed there.

**Closed by pavlenex** 2019-11-15 17:13 UTC
