### ISSUE TITLE
Support for ERC20 tokens

### ISSUE THREAD

**Issue by geraldz** [btcpayserver/btcpayserver-doc#108] opened 2018-11-11 15:28 UTC
Requesting support for ERC20 coins such as USDC and DAI.  DAI is currently supported on the Dappos App, can it be replicated here? https://github.com/Dappos/Dappos

**Comment by bitcoinshirt** [comment] 2018-11-11 15:42
1. Check this PR and see if you can help https://github.com/btcpayserver/btcpayserver/pull/158 
2. You can't request a coin to be added, as adding a new coin is up to community, [read this. ](https://docs.btcpayserver.org/faq-and-common-issues/faq-altcoin)

Also this is a documentation repo :-)

**Comment by Kukks** [comment] 2018-11-11 17:06
I'm not prioritizing the ethereum feature development but if the community can sponsor it, I will prioritize. 
The Dappos app is mostly just a frontend project that communicates with ether's Web3 so there's not much we can salvage from it. BtcPayServer has a much bigger/ different scope overall :)

**Comment by Code0Zero** [comment] 2018-11-12 15:17
Can anyone add monero to btcserver? It does make sense to add this privacy coin. Third party payment provider also do offer monero but there each IP gets logged.

**Comment by bitcoinshirt** [comment] 2018-11-13 07:41
The issue is now labeled as "prepare for closing" and will be closed it in the next 7 days if there's no further discussion.  If your question/problem was resolved, you can close the issue yourself. You can re-open the issue at any time.

**Closed** 2018-11-13 17:36 UTC
Labels: prepare-for-closing, question
