### ISSUE TITLE
Improve Raspberry Pi 3 Deployment

### ISSUE THREAD

**Issue by rafaelpac** [btcpayserver/btcpayserver-doc#717] opened 2020-09-16 02:41 UTC
I could not find the information I was looking for on the "Raspberry Pi 3 Deployment" page (`/RPi3/`).

1) If CONF_SWAPSIZE=2048, why would I need a 64GB USB swap drive?

2) Are there detailed instructions on how can I copy a full blockchain I synced on my laptop to the Raspi? Just stop both services and copy /blocks and /chainstate folders over?

**Comment by dennisreimann** [comment] 2020-09-16 06:05
Hey @rafaelpac, thanks for reporting these open questions. We'd like to consolidate the RPi deployment docs (#467) and these are good hints on how to improve them.

1. The USB thumb drive contains all BTCPay Server data, including the blockchain – so it's not just for the memory swap file. As the RPi3 is very limited in regards to memory, the `CONF_SWAPSIZE` defines how big the swap file should be. This file is for the case the internal RAM of the Raspberry Pi does not suffice.

2. AFAIK wee have not documented this particular use case – the closest I could find was this FAQ item on [how to symlink an existing full node data directory](https://docs.btcpayserver.org/FAQ/FAQ-Synchronization/#im-running-a-full-node-and-have-a-synched-blockchain-can-btcpay-use-it-so-that-it-doesnt-have-to-do-a-full-sync). However, it is very similar to this and basically like you described: Stop the services, copy the `blocks` and `chainstate` directories and restart.

**Comment by rafaelpac** [comment] 2020-09-16 13:51
Hi! Thanks. Somehow I had in my mind that the blockchain would be on a separate hard disk, but now I see that there is no hard disk on this setup. So the swap file and the pruned blockchain are both on the 64GB stick. So I assume that I can use a 500GB hard drive instead of the USB stick, right?

Another related question is why we would need a 16GB SDcard. Wouldn't 1GB be enough? (435MB for the Raspbian + fail2ban + ufw + docker...)

**Comment by pavlenex** [comment] 2020-10-19 08:09
Closing since this is a duplicate of #467, alternatively RPI3 docs should be removed and merged into RPI4 docs, but since both tutorials have clear and unclear sides, someone would need to test it out and re-write and use best from both worlds into a single doc - RPI.MD

**Closed by pavlenex** 2020-10-19 08:09 UTC
Labels: Discussion
